name: Compiler Explorer

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install prerequisites
        run: make prereqs
      - name: Run checks
        run: |
          npm run lint-check
          npm run ci-test
          npm run ts-check
          python3 ./etc/scripts/util/propscheck.py
      - name: Code coverage
        run: npm run codecov

  build_dist:
    if: github.repository_owner == 'compiler-explorer' && github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      release_name: ${{ steps.build_dist.outputs.release_name }}
      branch: ${{ steps.build_dist.outputs.branch }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Build distribution
        id: build_dist
        run: etc/scripts/build-dist.sh
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: out/dist-bin